apiVersion: v1
kind: Pod
metadata:
  name: test-1
spec:
  containers:
   - name: web-server
     image: nginx
     volumeMounts:
       - name: mypvc
         mountPath: /var/lib/www/html
       - name: stdpvc
         mountPath: /pvcstd
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: pvc-1
       readOnly: false
   - name: stdpvc
     persistentVolumeClaim:
       claimName: pvc-std
       readOnly: false

